name: cdiutils-env
channels:
  - conda-forge
dependencies:
  # core dependencies
  - python>=3.10
  - numpy
  - scipy>=1.8.0
  - matplotlib>=3.10
  - pandas>=1.4.2
  - scikit-image>=0.19.2
  - scikit-learn>=1.1.3
  - h5py>=3.6.0
  - hdf5plugin>=3.2.0
  - colorcet>=3.0.0
  - tabulate
  - silx
  - xrayutilities>=1.7.3
  
  # VTK dependencies
  - vtk>=9.0.1
  
  # interactive dependencies
  - ipywidgets
  - ipyvolume
  - bokeh
  - panel
  - tornado
  - pytables
  - h5glance
  - ipykernel
  - plotly>=5.0.0
  - anywidget
  - kaleido>=0.2.0
  
  # PyVista dependencies
  - pyvista>=0.43.0
  - trame>=3.0.0
  - trame-vuetify>=2.0.0
  - trame-vtk>=2.0.0
  
  # pip for packages not available on conda-forge (if any)
  - pip
  # - pip:
  #   - package_name
